baseURL = 'https://mate-111.web.app'
metaDataFormat = "yaml"
title = "Mate"
theme = "blist"
googleAnalytics = "G-BWNTC3FYDX"
IsMultiLingual = false

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Elevate Yourself!"
      introSubtitle = "Mate means 'I hear you', listen to your body and check out the posts below"
      introPhoto = "/images/matemasie-dark.png"
      logo = "/images/matemasie-dark.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

   

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/balancedBlackMen/"
        weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "Blist (mehrsprachig)"
    description = "Modernes Blog-Theme für Ihre Hugo-Site."
    [languages.de.params]
      introTitle = "Hallo, ich bin Katheryn Fox"
      introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo-de.png"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

  [languages.dy]
    contentDir = "content/dy" #Example language
    weight = 3
    languageName = "Test Language"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Mate · All rights reserved"
  

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"




[params.homepage.social]
  # Global params xommon for both languages
  title = "Find Us Elsewhere"
  description = "We create content to draw out the spirit within"
  twitter = "https://twitter.com/"
  instagram = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"
  

[[menu.main]]
  name = "About"
  url = "/page/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
